CREATE USER ozzu_app_user WITH PASSWORD 'ozzu_stage_user';

GRANT CONNECT ON DATABASE ozzu_dev TO ozzu_app_user;
GRANT USAGE ON SCHEMA public TO ozzu_app_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ozzu_app_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ozzu_app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ozzu_app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ozzu_app_user;